import { useEffect, useRef } from "react";
import type { OperationalRecoverySnapshot, RecoveryWorkflowStatus } from "../../domain/recovery/recoveryContracts";
import { RecoveryWorkflowStatuses } from "../../domain/recovery/recoveryContracts";
import { recoveryWorkflowCopy, type Locale } from "../../preferences/i18n/catalog";

export type RecoveryWorkflowAction = "approve" | "reject" | "reset";
type Failure = Readonly<{ code: string; message: string }>;
export type RecoveryWorkflowPanelProps = { actionFailure?: Failure; locale: Locale; onAction(action: RecoveryWorkflowAction): void; pending?: RecoveryWorkflowAction; refreshFailure?: Failure; snapshot?: OperationalRecoverySnapshot; snapshotFailure?: Failure };

const statusKey: Record<RecoveryWorkflowStatus, "comparisonAvailable" | "staged" | "awaiting" | "approved" | "rejected" | "invalidated" | "executed" | "verificationFailed" | "verified"> = { IDLE: "comparisonAvailable", STAGED: "staged", REVIEW_REQUESTED: "awaiting", APPROVED: "approved", REJECTED: "rejected", INVALIDATED: "invalidated", EXECUTED: "executed", VERIFICATION_FAILED: "verificationFailed", VERIFIED: "verified" };
const agentTool: Partial<Record<RecoveryWorkflowStatus, string>> = { APPROVED: "recovery_plan_execute", EXECUTED: "recovery_verify", VERIFICATION_FAILED: "recovery_verify", VERIFIED: "recovery_receipt_get" };
function shortFingerprint(value: string): string { return value.slice(0, 15) + "…" + value.slice(-6); }
function Evidence({ label, reason, status }: { label: string; reason: string; status: string }) { return <li><span>{label}</span><b data-status={status}>{status}</b><code>{reason}</code></li>; }

export function RecoveryWorkflowPanel({ actionFailure, locale, onAction, pending, refreshFailure, snapshot, snapshotFailure }: RecoveryWorkflowPanelProps) {
  const copy = recoveryWorkflowCopy(locale); const status = snapshot?.workflowStatus; const previousStatus = useRef(status); useEffect(() => { if (status === undefined || previousStatus.current === status) return; previousStatus.current = status; requestAnimationFrame(() => document.getElementById("recovery-workflow-status")?.focus()); }, [status]);
  if (snapshot === undefined || status === undefined) return <section className="workflow-state"><div className="workflow-error" role="alert"><strong>{copy.actionFailed}</strong><code>{snapshotFailure?.code ?? "REPOSITORY_FAILURE"}</code>{snapshotFailure && <p>{snapshotFailure.message}</p>}</div></section>;
  const plan = snapshot.plan; const grant = snapshot.approvalGrant; const execution = snapshot.executionRecord; const report = snapshot.verificationReport; const receipt = snapshot.receipt; const busy = pending !== undefined; const capability = agentTool[status]; const failure = actionFailure ?? refreshFailure;
  const action = (id: RecoveryWorkflowAction, label: string, tone = "") => <button className={tone} disabled={busy} onClick={() => onAction(id)} type="button">{label}</button>;
  const timeline = [[plan?.createdAt, copy.planEvidence], [grant?.approvedAt, copy.approval], [execution?.createdAt, copy.executionRecord], [report?.createdAt, copy.verification], [receipt?.createdAt, copy.receipt]].filter((entry): entry is [string, string] => typeof entry[0] === "string");
  return <section aria-label={copy.planEvidence} className="workflow-state"><header aria-live="polite" className="workflow-status"><h2 id="recovery-workflow-status" tabIndex={-1}>{copy[statusKey[status]]}</h2><code>{status}</code></header><p className="workflow-incident-status">{copy.incidentStatus}: <b>{snapshot.incident.status}</b></p>
    {capability && <p className="workflow-capability">{copy.agentCapabilityEnabled}: <code>{capability}</code></p>}
    {plan && <><section className="workflow-block"><h2>{copy.planEvidence}</h2><dl className="workflow-facts"><div><dt>{copy.planId}</dt><dd><code>{plan.planId}</code></dd></div><div><dt>{copy.basedOnRevision}</dt><dd>{plan.basedOnScenarioRevision}</dd></div><div><dt>{copy.scenarioRevision}</dt><dd>{snapshot.scenarioRevision}</dd></div><div><dt>{copy.fingerprint}</dt><dd><code title={plan.fingerprint}>{shortFingerprint(plan.fingerprint)}</code></dd></div><div><dt>{copy.currentRoute}</dt><dd><code>{plan.currentRouteId}</code></dd></div><div><dt>{copy.proposedRoute}</dt><dd><code>{plan.proposedRouteId}</code></dd></div></dl><dl className="workflow-constraints"><div><dt>{copy.clearanceBuffer}</dt><dd>{plan.hardConstraints.clearanceBufferMeters}</dd></div><div><dt>{copy.protectRestDeadline}</dt><dd><code>{plan.hardConstraints.protectRestDeadline ? copy.yes : copy.no}</code></dd></div><div><dt>{copy.keepCargoAssignment}</dt><dd><code>{plan.hardConstraints.keepCargoAssignment ? copy.yes : copy.no}</code></dd></div><div><dt>{copy.requireExclusionZoneAvoidance}</dt><dd><code>{plan.hardConstraints.requireExclusionZoneAvoidance ? copy.yes : copy.no}</code></dd></div></dl></section>
      <section className="workflow-block"><h2>{copy.hardResults}</h2><ul className="workflow-evidence"><Evidence label={copy.currentClearance} reason={plan.constraintResults.currentClearance.data.reasonCode} status={plan.constraintResults.currentClearance.data.status} /><Evidence label={copy.proposedClearance} reason={plan.constraintResults.proposedClearance.reasonCode} status={plan.constraintResults.proposedClearance.status} /><Evidence label={copy.proposedAvoidance} reason={plan.constraintResults.proposedAvoidance.reasonCode} status={plan.constraintResults.proposedAvoidance.status} /><Evidence label={copy.proposedTemporal} reason={plan.constraintResults.proposedTemporal.reasonCode} status={plan.constraintResults.proposedTemporal.status} /><Evidence label={copy.proposedCargoContinuity} reason={plan.constraintResults.proposedCargoContinuity.reasonCode} status={plan.constraintResults.proposedCargoContinuity.status} /></ul><dl className="workflow-facts"><div><dt>{copy.currentMetrics}</dt><dd>{plan.metrics.current.distanceMeters} m · {plan.metrics.current.durationSeconds} s</dd></div><div><dt>{copy.proposedMetrics}</dt><dd>{plan.metrics.proposed.distanceMeters} m · {plan.metrics.proposed.durationSeconds} s</dd></div></dl></section></>}
    {grant && <section className="workflow-block"><h2>{copy.approval}</h2><p><code>{grant.approvedBy}</code> · {grant.approvedAt} · {copy.used}: <code>{grant.used ? copy.yes : copy.no}</code></p></section>}
    {execution && <section className="workflow-block"><h2>{copy.executionRecord}</h2><p><code>{execution.executionId}</code></p><p>{execution.previousRouteId} → {execution.appliedRouteId} · {execution.beforeRevision} → {execution.afterRevision}</p></section>}
    {report && <section className="workflow-block"><h2>{copy.verification}</h2><ul className="verification-matrix">{report.checks.map((check) => <li key={check.name}><code>{check.name}</code><b data-status={check.status}>{check.status}</b></li>)}</ul></section>}
    {receipt && <section className="workflow-block workflow-receipt"><h2>{copy.receipt}</h2><p><code>{receipt.receiptId}</code></p><dl className="workflow-facts"><div><dt>{copy.previousAppliedRoute}</dt><dd>{receipt.previousRouteId} → {receipt.appliedRouteId}</dd></div><div><dt>{copy.beforeAfterRevision}</dt><dd>{receipt.beforeRevision} → {receipt.afterRevision}</dd></div><div><dt>{copy.humanApproval}</dt><dd><code>{receipt.approvalSource}</code></dd></div><div><dt>{copy.executionOnce}</dt><dd>{snapshot.executionEffects.length}</dd></div><div><dt>{copy.verificationResult}</dt><dd><b data-status={receipt.verificationReport.status}>{receipt.verificationReport.status}</b></dd></div></dl></section>}
    {timeline.length > 0 && <section className="workflow-block"><h2>{copy.activity}</h2><ol className="workflow-activity">{timeline.map(([date, label], index) => <li key={label + ":" + index}><span>{label}</span><time dateTime={date}>{date}</time></li>)}</ol></section>}
    {(status === RecoveryWorkflowStatuses.rejected || status === RecoveryWorkflowStatuses.invalidated) && <p className="workflow-audit-note">{copy.noAudit}</p>}{failure && <div className="workflow-error" role="alert"><strong>{copy.actionFailed}</strong><code>{failure.code}</code><p>{failure.message}</p></div>}
    <div aria-busy={busy} className="workflow-actions">{status === RecoveryWorkflowStatuses.reviewRequested && <>{action("approve", copy.approve, "workflow-primary")}{action("reject", copy.reject, "workflow-danger")}</>}{status !== RecoveryWorkflowStatuses.idle && action("reset", copy.resetDemo)}</div>
  </section>;
}
