import { LockKey, MapTrifold, WarningCircle } from "@phosphor-icons/react";
import type { Unit211PreDispatchContextFailureReason } from "../../domain/operations/unit211PreDispatchContext";
import { catalog, interpolate, recoveryComparisonCopy, type Locale } from "../../preferences/i18n/catalog";
import type { Unit211RecoveryComparisonModel } from "./unit211RecoveryComparisonModel";

type RouteEvidence = Unit211RecoveryComparisonModel["current"] | Unit211RecoveryComparisonModel["alternative"];
type CargoFacts = Exclude<RouteEvidence["cargoContinuity"], { status: "UNKNOWN" }>["optionFacts"];
function value(value: number | string | null, locale: Locale, suffix = ""): string { return value === null ? recoveryComparisonCopy(locale).notAvailable : `${typeof value === "number" ? new Intl.NumberFormat(locale === "es" ? "es-ES" : "en-GB", { maximumFractionDigits: 2 }).format(value) : value}${suffix}`; }
function refrigeration(value: CargoFacts["refrigeration"], locale: Locale): string { const copy = catalog(locale); return value === "chilled" ? copy.chilled : value === "frozen" ? copy.frozen : copy.ambient; }
function priority(value: CargoFacts["priority"], locale: Locale): string { const copy = catalog(locale); return value === "priority" ? copy.priorityUrgent : value === "critical" ? copy.priorityCritical : copy.priorityStandard; }
function RouteEvidence({ locale, route }: { locale: Locale; route: RouteEvidence }) { const copy = recoveryComparisonCopy(locale); const cargo = route.cargoContinuity; const facts = (item: CargoFacts) => `${copy.vehicleId}: ${item.vehicleId} · ${copy.cargoId}: ${item.cargoId} · ${copy.destinationId}: ${item.destinationId}`; return <div className="assessment-grid"><section aria-label={copy.temporalAssessment}><div className="assessment-heading"><strong>{copy.temporalAssessment}</strong><b data-status={route.temporal.status}>{route.temporal.status}</b></div><code>{route.temporal.reasonCode}</code><dl><div><dt>{copy.remainingRoute}</dt><dd>{value(route.temporal.remainingRouteMinutes, locale, " min")}</dd></div><div><dt>{copy.remainingDrive}</dt><dd>{value(route.temporal.remainingDriveMinutes, locale, " min")}</dd></div><div><dt>{copy.estimatedCompletion}</dt><dd>{value(route.temporal.estimatedCompletionAt, locale)}</dd></div><div><dt>{copy.restDeadline}</dt><dd>{value(route.temporal.restDeadline, locale)}</dd></div></dl></section><section aria-label={copy.cargoContinuity}><div className="assessment-heading"><strong>{copy.cargoContinuity}</strong><b data-status={cargo.status}>{cargo.status}</b></div><code>{cargo.reasonCode}</code>{cargo.status === "UNKNOWN" ? <dl><div><dt>{copy.source}</dt><dd>{cargo.source}</dd></div><div><dt>{copy.reasonCode}</dt><dd>{cargo.sourceReasonCode}</dd></div></dl> : <><dl><div><dt>{copy.reference}</dt><dd>{facts(cargo.referenceFacts)}</dd></div><div><dt>{copy.option}</dt><dd>{facts(cargo.optionFacts)}</dd></div><div><dt>{copy.refrigeration}</dt><dd>{refrigeration(cargo.optionFacts.refrigeration, locale)}</dd></div><div><dt>{copy.priority}</dt><dd>{priority(cargo.optionFacts.priority, locale)}</dd></div></dl>{cargo.status === "FAIL" && <p>{cargo.mismatchReasonCodes.join(", ")}</p>}</>}</section></div>; }
function RouteMetrics({ distance, duration, locale }: { distance: string; duration: string; locale: Locale }) { const copy = recoveryComparisonCopy(locale); return <dl className="route-metrics"><div><dt>{copy.distance}</dt><dd>{distance}</dd></div><div><dt>{copy.duration}</dt><dd>{duration}</dd></div></dl>; }

export function RecoveryComparisonFailure({ locale, reasonCode }: { locale: Locale; reasonCode: Unit211PreDispatchContextFailureReason }) { const copy = recoveryComparisonCopy(locale); return <section aria-labelledby="recovery-comparison-heading" className="recovery-comparison-failure" role="alert"><h1 id="recovery-comparison-heading" tabIndex={-1}>{copy.failureTitle}</h1><p>{copy.failureDescription}</p><dl><dt>{copy.reasonCode}</dt><dd><code>{reasonCode}</code></dd></dl><p className="recovery-failure-assurance">{copy.noRouteChanged}</p></section>; }

export function RecoveryComparisonPanel({ locale, model }: { locale: Locale; model: Unit211RecoveryComparisonModel }) {
  const copy = recoveryComparisonCopy(locale); const meters = (value: number) => new Intl.NumberFormat(locale === "es" ? "es-ES" : "en-GB", { maximumFractionDigits: 2, minimumFractionDigits: 2 }).format(value);
  return <section aria-labelledby="recovery-comparison-heading" className="recovery-panel-view">
    <header className="recovery-panel-header"><div className="recovery-eyebrow"><span>{copy.visualReview}</span><span>{copy.domainConnected}</span></div><h1 id="recovery-comparison-heading" tabIndex={-1}>{copy.comparison}</h1><p><strong>{model.vehicle.displayLabel}</strong> · {model.vehicle.fleetNumber} · {model.vehicle.location} · {model.vehicle.state}</p><p><time dateTime={model.scenarioClock.instant}>{model.scenarioClock.instant}</time> · {model.scenarioClock.mode}</p></header>
    <div className="recovery-panel-body"><section aria-labelledby="incident-heading" className="incident-card"><div className="section-heading"><WarningCircle aria-hidden="true" size={20} weight="fill" /><h2 id="incident-heading">{copy.clearanceIncident}</h2><span>{model.clearance.status}</span></div><p>{interpolate(copy.currentRouteIncident, { restriction: meters(model.incident.restrictionMeters) })}</p><output aria-label={copy.required} className="clearance-equation">{model.clearance.equation}</output><p className="rejection-reason"><code>{model.clearance.reasonCode}</code> · {copy.rejectionExplanation}</p></section>
      <section aria-labelledby="constraints-heading" className="recovery-section"><div className="section-heading"><LockKey aria-hidden="true" size={18} /><h2 id="constraints-heading">{copy.hardConstraints}</h2></div><dl className="constraint-list"><div><dt>{copy.vehicleHeight}</dt><dd>{meters(model.clearance.vehicleHeightMeters)} m</dd></div><div><dt>{copy.safetyMargin}</dt><dd>{meters(model.clearance.humanBufferMeters)} m</dd></div><div><dt>{copy.required}</dt><dd>{meters(model.clearance.requiredMeters)} m</dd></div></dl><p className="constraint-note">{copy.bufferSupplied}</p></section>
      <section aria-labelledby="options-heading" className="recovery-section"><div className="section-heading"><MapTrifold aria-hidden="true" size={18} /><h2 id="options-heading">{copy.routeOptions}</h2></div><article aria-label={`${copy.keepCurrent}, ${model.current.statusLabel}`} className="route-option route-option-rejected"><div className="option-heading"><div><span>{copy.keepCurrent}</span><code>{model.current.id}</code></div><b>{model.current.statusLabel}</b></div><RouteMetrics distance={model.current.distance} duration={model.current.duration} locale={locale} /><p>{model.clearance.reasonCode}</p><RouteEvidence locale={locale} route={model.current} /></article><article aria-label={`${copy.useAlternative}, ${model.alternative.statusLabel}`} className="route-option route-option-valid"><div className="option-heading"><div><span>{copy.useAlternative}</span><code>{model.alternative.id}</code></div><b>{model.alternative.statusLabel}</b></div><RouteMetrics distance={model.alternative.distance} duration={model.alternative.duration} locale={locale} /><p>{model.alternative.avoidsExclusionZone ? copy.alternativeAvoids : copy.alternativeAvoidanceUnknown}</p><RouteEvidence locale={locale} route={model.alternative} /></article></section></div>
  </section>;
}
