import { CheckCircle, Info, LockKey, MapTrifold, WarningCircle } from "@phosphor-icons/react";
import type { Unit211PreDispatchContextFailureReason } from "../../domain/operations/unit211PreDispatchContext";
import { interpolate, recoveryComparisonCopy, type Locale } from "../../preferences/i18n/catalog";
import type { Unit211RecoveryComparisonModel } from "./unit211RecoveryComparisonModel";

function RouteMetrics({ distance, duration, locale }: { distance: string; duration: string; locale: Locale }) { const copy = recoveryComparisonCopy(locale); return <dl className="route-metrics"><div><dt>{copy.distance}</dt><dd>{distance}</dd></div><div><dt>{copy.duration}</dt><dd>{duration}</dd></div></dl>; }

export function RecoveryComparisonFailure({ locale, reasonCode }: { locale: Locale; reasonCode: Unit211PreDispatchContextFailureReason }) { const copy = recoveryComparisonCopy(locale); return <section aria-labelledby="recovery-comparison-heading" className="recovery-preview-error recovery-comparison-failure" role="alert"><h1 id="recovery-comparison-heading" tabIndex={-1}>{copy.failureTitle}</h1><p>{copy.failureDescription}</p><dl><dt>{copy.reasonCode}</dt><dd><code>{reasonCode}</code></dd></dl><p className="recovery-preview-error-assurance">{copy.noRouteChanged}</p></section>; }

export function RecoveryComparisonPanel({ locale, model, showPreviewAction = false }: { locale: Locale; model: Unit211RecoveryComparisonModel; showPreviewAction?: boolean }) {
  const copy = recoveryComparisonCopy(locale); const meters = (value: number) => new Intl.NumberFormat(locale === "es" ? "es-ES" : "en-GB", { maximumFractionDigits: 2, minimumFractionDigits: 2 }).format(value);
  return <section aria-labelledby="recovery-comparison-heading" className="recovery-panel-view">
    <header className="recovery-panel-header"><div className="preview-eyebrow"><span>{copy.visualReview}</span><span>{copy.domainConnected}</span></div><h1 id="recovery-comparison-heading" tabIndex={-1}>{copy.comparison}</h1><p><strong>{model.vehicle.displayLabel}</strong> · {model.vehicle.fleetNumber} · {model.vehicle.location} · {model.vehicle.state}</p><p><time dateTime={model.scenarioClock.instant}>{model.scenarioClock.instant}</time> · {model.scenarioClock.mode}</p></header>
    <div className="recovery-panel-body"><section aria-labelledby="incident-heading" className="incident-card"><div className="section-heading"><WarningCircle aria-hidden="true" size={20} weight="fill" /><h2 id="incident-heading">{copy.clearanceIncident}</h2><span>{model.clearance.status}</span></div><p>{interpolate(copy.currentRouteIncident, { restriction: meters(model.incident.restrictionMeters) })}</p><output aria-label={copy.required} className="clearance-equation">{model.clearance.equation}</output><p className="rejection-reason"><code>{model.clearance.reasonCode}</code> · {copy.rejectionExplanation}</p></section>
      <section aria-labelledby="constraints-heading" className="recovery-section"><div className="section-heading"><LockKey aria-hidden="true" size={18} /><h2 id="constraints-heading">{copy.hardConstraints}</h2></div><dl className="constraint-list"><div><dt>{copy.vehicleHeight}</dt><dd>{meters(model.clearance.vehicleHeightMeters)} m</dd></div><div><dt>{copy.safetyMargin}</dt><dd>{meters(model.clearance.humanBufferMeters)} m</dd></div><div><dt>{copy.required}</dt><dd>{meters(model.clearance.requiredMeters)} m</dd></div></dl><p className="constraint-note">{copy.bufferSupplied}</p></section>
      <section aria-labelledby="options-heading" className="recovery-section"><div className="section-heading"><MapTrifold aria-hidden="true" size={18} /><h2 id="options-heading">{copy.routeOptions}</h2></div><article aria-disabled="true" aria-label={`${copy.keepCurrent}, ${model.current.statusLabel}`} className="route-option route-option-rejected"><div className="option-heading"><div><span>{copy.keepCurrent}</span><code>{model.current.id}</code></div><b>{model.current.statusLabel}</b></div><RouteMetrics distance={model.current.distance} duration={model.current.duration} locale={locale} /><p>{model.clearance.reasonCode}</p></article><article aria-label={`${copy.useAlternative}, ${model.alternative.statusLabel}`} className="route-option route-option-valid"><div className="option-heading"><div><span>{copy.useAlternative}</span><code>{model.alternative.id}</code></div><b>{model.alternative.statusLabel}</b></div><RouteMetrics distance={model.alternative.distance} duration={model.alternative.duration} locale={locale} /><p>{model.alternative.avoidsExclusionZone ? copy.alternativeAvoids : copy.alternativeAvoidanceUnknown} <strong>{model.delta.distance} · {model.delta.duration}</strong></p></article></section>
      <div className="evidence-grid"><section aria-labelledby="resolved-heading"><div className="section-heading"><CheckCircle aria-hidden="true" size={18} weight="fill" /><h2 id="resolved-heading">{copy.resolvedRisk}</h2></div><ul>{model.resolvedRisks.map((item) => <li key={item}>{item}</li>)}</ul></section><section aria-labelledby="unknown-heading"><div className="section-heading"><Info aria-hidden="true" size={18} weight="fill" /><h2 id="unknown-heading">{copy.stillUnknown}</h2></div>{model.unknownData.length === 0 ? <p>{copy.noUnknown}</p> : <ul>{model.unknownData.map((item) => <li key={item}>{item}</li>)}</ul>}</section></div></div>
    {showPreviewAction && <footer className="recovery-action-preview"><button disabled type="button">{copy.preparePlan}</button><p>{copy.previewOnly}</p></footer>}
  </section>;
}
