import { CheckCircle, Info, LockKey, MapTrifold, WarningCircle } from "@phosphor-icons/react";
import type { Unit211RecoveryPreviewModel } from "./unit211RecoveryPreviewModel";

function RouteMetrics({ distance, duration }: { distance: string; duration: string }) { return <dl className="route-metrics"><div><dt>Distance</dt><dd>{distance}</dd></div><div><dt>Duration</dt><dd>{duration}</dd></div></dl>; }

export function RecoveryComparisonPanel({ model }: { model: Unit211RecoveryPreviewModel }) {
  return <aside aria-labelledby="recovery-comparison-heading" className="recovery-panel">
    <header className="recovery-panel-header"><div className="preview-eyebrow"><span>Development preview</span><span>Domain connected</span></div><h1 id="recovery-comparison-heading">Recovery comparison</h1><p><strong>{model.vehicle.displayLabel}</strong> · {model.vehicle.fleetNumber} · {model.vehicle.location} · {model.vehicle.state}</p><p><time dateTime={model.scenarioClock.instant}>{model.scenarioClock.instant}</time> · {model.scenarioClock.mode}</p></header>
    <div className="recovery-panel-body">
      <section aria-labelledby="incident-heading" className="incident-card"><div className="section-heading"><WarningCircle aria-hidden="true" size={20} weight="fill" /><h2 id="incident-heading">Clearance incident</h2><span>{model.clearance.status}</span></div><p>The current route reaches a {model.incident.restrictionMeters.toFixed(2)} m clearance before departure.</p><output aria-label="Required clearance calculation" className="clearance-equation">{model.clearance.equation}</output><p className="rejection-reason"><code>{model.clearance.reasonCode}</code> · Required clearance exceeds the mapped restriction.</p></section>
      <section aria-labelledby="constraints-heading" className="recovery-section"><div className="section-heading"><LockKey aria-hidden="true" size={18} /><h2 id="constraints-heading">Hard human constraints</h2></div><dl className="constraint-list"><div><dt>Vehicle height</dt><dd>{model.clearance.vehicleHeightMeters.toFixed(2)} m</dd></div><div><dt>Safety margin</dt><dd>{model.clearance.humanBufferMeters.toFixed(2)} m</dd></div><div><dt>Required</dt><dd>{model.clearance.requiredMeters.toFixed(2)} m</dd></div></dl><p className="constraint-note">Clearance buffer supplied by the pre-dispatch operation.</p></section>
      <section aria-labelledby="options-heading" className="recovery-section"><div className="section-heading"><MapTrifold aria-hidden="true" size={18} /><h2 id="options-heading">Route options</h2></div>
        <article aria-disabled="true" aria-label={`Keep current route, ${model.current.status}`} className="route-option route-option-rejected"><div className="option-heading"><div><span>Keep current route</span><code>{model.current.id}</code></div><b>{model.current.status}</b></div><RouteMetrics distance={model.current.distance} duration={model.current.duration} /><p>{model.clearance.reasonCode}</p></article>
        <article aria-label={`Use alternative route, ${model.alternative.status}`} className="route-option route-option-valid"><div className="option-heading"><div><span>Use alternative route</span><code>{model.alternative.id}</code></div><b>{model.alternative.status}</b></div><RouteMetrics distance={model.alternative.distance} duration={model.alternative.duration} /><p>{model.alternative.avoidsExclusionZone ? "Avoids the mapped exclusion zone." : "Exclusion-zone avoidance is not confirmed."} <strong>{model.delta.distance} · {model.delta.duration}</strong></p></article>
      </section>
      <div className="evidence-grid"><section aria-labelledby="resolved-heading"><div className="section-heading"><CheckCircle aria-hidden="true" size={18} weight="fill" /><h2 id="resolved-heading">Resolved risk</h2></div><ul>{model.resolvedRisks.map((item) => <li key={item}>{item}</li>)}</ul></section><section aria-labelledby="unknown-heading"><div className="section-heading"><Info aria-hidden="true" size={18} weight="fill" /><h2 id="unknown-heading">Still unknown</h2></div>{model.unknownData.length === 0 ? <p>No additional uncertainty fields were returned by this operation.</p> : <ul>{model.unknownData.map((item) => <li key={item}>{item}</li>)}</ul>}</section></div>
    </div>
    <footer className="recovery-action-preview"><button disabled type="button">Prepare plan</button><p>Preview only — no plan will be prepared.</p></footer>
  </aside>;
}
