import type { FilterCategory } from "../../app/state/useUiCoordinationStore";
import { en } from "./en";
import { es } from "./es";

export const locales = ["en", "es"] as const;
export type Locale = (typeof locales)[number];
export type Catalog = {
  account: string; actions: string; all: string; ambient: string; approximateDistance: string; cancel: string; cargo: string; cargoTab: string; chilled: string; clearanceComparison: string; closeInspection: string; closeResults: string; collapseRail: string; expandRail: string; consoleControls: string; consoleUnavailable: string; critical: string; currentRisk: string; currentRoute: string; delay: string; delete: string; deleteConsequence: string; deleteVehicle: string; destination: string; dimensions: string; driverTab: string; driving: string; drivingRestRisk: string; eta: string; fleetFilters: string; fleetNumber: string; followVehicle: string; frozen: string; help: string; heightComparison: string; hoursShort: string; identity: string; impact: string; invalidLabel: string; label: string; labelSaved: string; language: string; languageEnglish: string; languageSpanish: string; length: string; meters: string; minutes: string; minutesShort: string; needsAttention: string; noCurrentRisk: string; notAvailable: string; operationalMap: string; operationalSummary: string; origin: string; plate: string; priority: string; priorityCritical: string; priorityStandard: string; priorityUrgent: string; refrigeration: string; remainingDrive: string; restDeadline: string; resting: string; retry: string; riskClosure: string; riskComparison: string; riskHeight: string; riskImpactClosure: string; riskImpactHeight: string; riskImpactRest: string; riskImpactSnow: string; riskImpactWeight: string; riskRest: string; riskSnow: string; riskWeight: string; roadRestrictionIssues: string; route: string; saveLabel: string; selectVehicle: string; status: string; statusCritical: string; statusDriving: string; statusNeedsAttention: string; statusResting: string; tonnes: string; vehicleHeight: string; vehicleInspection: string; vehicleTab: string; vehicleType: string; viewOnRoute: string; weatherAffected: string; webMcpChecking: string; webMcpRequired: string; weight: string; whyAttention: string;
};

const catalogs: Record<Locale, Catalog> = { en, es };
const filterKeys: Record<FilterCategory, keyof Catalog> = { all: "all", resting: "resting", "needs-attention": "needsAttention", critical: "critical", "weather-affected": "weatherAffected", "driving-rest-risk": "drivingRestRisk", "road-restriction-issues": "roadRestrictionIssues" };

export function catalog(locale: Locale = "en"): Catalog { return catalogs[locale]; }
export function filterLabel(category: FilterCategory, locale: Locale = "en"): string { return catalog(locale)[filterKeys[category]]; }
export function interpolate(template: string, values: Record<string, string | number>): string { return Object.entries(values).reduce((message, [key, value]) => message.replaceAll(`{${key}}`, String(value)), template); }

export type OperationalCopy = { activeFilters: string; closeOverview: string; lowClearance: string; openOverview: string; operationalOverview: string; removeFilter: string; restDeadlineRisk: string; roadClosure: string; severeWeather: string; severityCritical: string; severityHigh: string; severityLow: string; severityMedium: string; weightRestriction: string };
const operationalCatalogs: Record<Locale, OperationalCopy> = {
  en: { activeFilters: "{count} active filters", closeOverview: "Close operational overview", lowClearance: "Low clearance", openOverview: "Open operational overview", operationalOverview: "Operational overview", removeFilter: "Remove {filter}", restDeadlineRisk: "Driving and rest deadline", roadClosure: "Road closure", severeWeather: "Severe weather", severityCritical: "Critical", severityHigh: "High", severityLow: "Low", severityMedium: "Medium", weightRestriction: "Weight restriction" },
  es: { activeFilters: "{count} filtros activos", closeOverview: "Cerrar resumen operativo", lowClearance: "Gálibo reducido", openOverview: "Abrir resumen operativo", operationalOverview: "Resumen operativo", removeFilter: "Quitar {filter}", restDeadlineRisk: "Límite de conducción y descanso", roadClosure: "Carretera cerrada", severeWeather: "Meteorología adversa", severityCritical: "Crítica", severityHigh: "Alta", severityLow: "Baja", severityMedium: "Media", weightRestriction: "Restricción de peso" },
};
export function operationalCopy(locale: Locale): OperationalCopy { return operationalCatalogs[locale]; }

export type RecoveryComparisonCopy = { alternative: string; alternativeAvoids: string; alternativeAvoidanceUnknown: string; backToVehicleDetails: string; beforeDeparture: string; bufferSupplied: string; cargoContinuity: string; cargoId: string; clearanceIncident: string; comparison: string; current: string; currentRouteIncident: string; destinationId: string; distance: string; domainConnected: string; duration: string; estimatedCompletion: string; exclusionZone: string; exactZone: string; failureDescription: string; failureTitle: string; hardConstraints: string; incident: string; incidentDetail: string; keepCurrent: string; noRouteChanged: string; notAvailable: string; option: string; priority: string; reasonCode: string; reference: string; refrigeration: string; rejected: string; rejectionExplanation: string; remainingDrive: string; remainingRoute: string; required: string; requiredSuffix: string; restDeadline: string; reviewOptions: string; routeOptions: string; routeStarted: string; safetyMargin: string; selectIncident: string; source: string; supported: string; temporalAssessment: string; useAlternative: string; vehicleHeight: string; vehicleId: string; visualReview: string };
const recoveryComparisonCatalogs: Record<Locale, RecoveryComparisonCopy> = {
  en: { alternative: "Alternative", alternativeAvoids: "Avoids the mapped exclusion zone.", alternativeAvoidanceUnknown: "Exclusion-zone avoidance is not confirmed.", backToVehicleDetails: "Back to vehicle details", beforeDeparture: "Before departure", bufferSupplied: "Clearance buffer supplied by the pre-dispatch operation.", cargoContinuity: "Cargo continuity", cargoId: "Cargo ID", clearanceIncident: "Clearance incident", comparison: "Recovery comparison", current: "Current", currentRouteIncident: "The current route reaches a {restriction} m clearance before departure.", destinationId: "Destination ID", distance: "Distance", domainConnected: "Domain connected", duration: "Duration", estimatedCompletion: "Estimated completion", exclusionZone: "Exclusion zone", exactZone: "Exact {radius} m zone", failureDescription: "The pre-dispatch operation returned a structured failure, so route options cannot be shown safely.", failureTitle: "Recovery comparison unavailable", hardConstraints: "Hard human constraints", incident: "{restriction} m incident", incidentDetail: "Incident detail", keepCurrent: "Keep current route", noRouteChanged: "No route was changed.", notAvailable: "Not available", option: "Option", priority: "Priority", reasonCode: "Reason code", reference: "Reference", refrigeration: "Refrigeration", rejected: "Rejected", rejectionExplanation: "Required clearance exceeds the mapped restriction.", remainingDrive: "Available drive time", remainingRoute: "Remaining route time", required: "Required", requiredSuffix: "m required", restDeadline: "Rest deadline", reviewOptions: "Review recovery options", routeOptions: "Route options", routeStarted: "Route started", safetyMargin: "Safety margin", selectIncident: "Select Unit 211 clearance incident", source: "Source", supported: "Supported for comparison", temporalAssessment: "Temporal assessment", useAlternative: "Use alternative route", vehicleHeight: "Vehicle height", vehicleId: "Vehicle ID", visualReview: "Visual review" },
  es: { alternative: "Alternativa", alternativeAvoids: "Evita la zona de exclusión cartografiada.", alternativeAvoidanceUnknown: "No se ha confirmado que evite la zona de exclusión.", backToVehicleDetails: "Volver al detalle del vehículo", beforeDeparture: "Antes de la salida", bufferSupplied: "Margen de gálibo suministrado por la operación previa a la salida.", cargoContinuity: "Continuidad de carga", cargoId: "ID de carga", clearanceIncident: "Incidencia de gálibo", comparison: "Comparación de recuperación", current: "Actual", currentRouteIncident: "La ruta actual alcanza un gálibo de {restriction} m antes de la salida.", destinationId: "ID de destino", distance: "Distancia", domainConnected: "Conectada al dominio", duration: "Duración", estimatedCompletion: "Finalización estimada", exclusionZone: "Zona de exclusión", exactZone: "Zona exacta de {radius} m", failureDescription: "La operación previa a la salida devolvió un fallo estructurado, por lo que las opciones de ruta no pueden mostrarse de forma segura.", failureTitle: "Comparación de recuperación no disponible", hardConstraints: "Restricciones humanas estrictas", incident: "Incidencia de {restriction} m", incidentDetail: "Detalle de la incidencia", keepCurrent: "Mantener la ruta actual", noRouteChanged: "No se modificó ninguna ruta.", notAvailable: "No disponible", option: "Opción", priority: "Prioridad", reasonCode: "Código de motivo", reference: "Referencia", refrigeration: "Refrigeración", rejected: "Rechazada", rejectionExplanation: "El gálibo requerido supera la restricción cartografiada.", remainingDrive: "Conducción disponible", remainingRoute: "Ruta restante", required: "Requerido", requiredSuffix: "m requeridos", restDeadline: "Límite de descanso", reviewOptions: "Revisar opciones de recuperación", routeOptions: "Opciones de ruta", routeStarted: "Ruta iniciada", safetyMargin: "Margen de seguridad", selectIncident: "Seleccionar incidencia de gálibo de Unit 211", source: "Fuente", supported: "Compatible para comparar", temporalAssessment: "Evaluación temporal", useAlternative: "Usar la ruta alternativa", vehicleHeight: "Altura del vehículo", vehicleId: "ID de vehículo", visualReview: "Revisión visual" },
};
export function recoveryComparisonCopy(locale: Locale): RecoveryComparisonCopy { return recoveryComparisonCatalogs[locale]; }

export type RecoveryWorkflowCopy = { actionFailed: string; activity: string; agentCapabilityEnabled: string; approval: string; approve: string; approved: string; awaiting: string; basedOnRevision: string; beforeAfterRevision: string; clearanceBuffer: string; comparisonAvailable: string; currentClearance: string; currentMetrics: string; currentRoute: string; executed: string; executionOnce: string; executionRecord: string; fingerprint: string; hardResults: string; humanApproval: string; incidentStatus: string; invalidated: string; keepCargoAssignment: string; no: string; noAudit: string; planEvidence: string; planId: string; previousAppliedRoute: string; proposedAvoidance: string; proposedCargoContinuity: string; proposedClearance: string; proposedMetrics: string; proposedRoute: string; proposedTemporal: string; protectRestDeadline: string; receipt: string; rejected: string; reject: string; requireExclusionZoneAvoidance: string; resetDemo: string; scenarioRevision: string; staged: string; used: string; verification: string; verificationFailed: string; verificationResult: string; verified: string; yes: string };
const recoveryWorkflowCatalogs: Record<Locale, RecoveryWorkflowCopy> = {
  en: { actionFailed: "The operation failed", activity: "Authoritative evidence", agentCapabilityEnabled: "Agent capability enabled", approval: "Authorization", approve: "Approve", approved: "Approved", awaiting: "Awaiting human review", basedOnRevision: "Based on scenario revision", beforeAfterRevision: "Before / after revision", clearanceBuffer: "Clearance buffer", comparisonAvailable: "Comparison available", currentClearance: "Current clearance", currentMetrics: "Current route distance / duration", currentRoute: "Previous/current route", executed: "Executed", executionOnce: "Execution effects", executionRecord: "Execution record", fingerprint: "Fingerprint", hardResults: "Hard-constraint results", humanApproval: "Human approval", incidentStatus: "Incident", invalidated: "Invalidated", keepCargoAssignment: "Keep cargo assignment", no: "No", noAudit: "No actor, timestamp, or reason is available for this status.", planEvidence: "Plan evidence", planId: "Plan ID", previousAppliedRoute: "Previous / applied route", proposedAvoidance: "Proposed avoidance", proposedCargoContinuity: "Proposed cargo continuity", proposedClearance: "Proposed clearance", proposedMetrics: "Proposed route distance / duration", proposedRoute: "Proposed route", proposedTemporal: "Proposed temporal result", protectRestDeadline: "Protect rest deadline", receipt: "Verified receipt", rejected: "Rejected", reject: "Reject", requireExclusionZoneAvoidance: "Require exclusion-zone avoidance", resetDemo: "Reset demo", scenarioRevision: "Current scenario revision", staged: "Plan staged", used: "Used", verification: "Verification matrix", verificationFailed: "Verification failed", verificationResult: "Verification result", verified: "Verified", yes: "Yes" },
  es: { actionFailed: "La operación ha fallado", activity: "Evidencia autoritativa", agentCapabilityEnabled: "Capacidad del agente habilitada", approval: "Autorización", approve: "Aprobar", approved: "Aprobado", awaiting: "Pendiente de revisión humana", basedOnRevision: "Basado en la revisión del escenario", beforeAfterRevision: "Revisión anterior / posterior", clearanceBuffer: "Margen de gálibo", comparisonAvailable: "Comparación disponible", currentClearance: "Gálibo de la ruta actual", currentMetrics: "Distancia / duración de ruta actual", currentRoute: "Ruta anterior/actual", executed: "Ejecutado", executionOnce: "Efectos de ejecución", executionRecord: "Registro de ejecución", fingerprint: "Huella", hardResults: "Resultados de restricciones estrictas", humanApproval: "Aprobación humana", incidentStatus: "Incidencia", invalidated: "Invalidado", keepCargoAssignment: "Mantener la asignación de carga", no: "No", noAudit: "No hay actor, fecha ni motivo disponibles para este estado.", planEvidence: "Evidencia del plan", planId: "ID del plan", previousAppliedRoute: "Ruta anterior / aplicada", proposedAvoidance: "Evitación propuesta", proposedCargoContinuity: "Continuidad de carga propuesta", proposedClearance: "Gálibo de la ruta propuesta", proposedMetrics: "Distancia / duración de ruta propuesta", proposedRoute: "Ruta propuesta", proposedTemporal: "Resultado temporal propuesto", protectRestDeadline: "Proteger el límite de descanso", receipt: "Recibo verificado", rejected: "Rechazado", reject: "Rechazar", requireExclusionZoneAvoidance: "Exigir evitar la zona de exclusión", resetDemo: "Reiniciar demo", scenarioRevision: "Revisión actual del escenario", staged: "Plan preparado", used: "Usada", verification: "Matriz de verificación", verificationFailed: "Verificación fallida", verificationResult: "Resultado de verificación", verified: "Verificado", yes: "Sí" },
};
export function recoveryWorkflowCopy(locale: Locale): RecoveryWorkflowCopy { return recoveryWorkflowCatalogs[locale]; }
