import type { FilterCategory } from "../../app/state/useUiCoordinationStore";
import { en } from "./en";
import { es } from "./es";

export const locales = ["en", "es"] as const;
export type Locale = (typeof locales)[number];
export type Catalog = {
  account: string; actions: string; all: string; ambient: string; approximateDistance: string; cancel: string; cargo: string; cargoTab: string; chilled: string; clearanceComparison: string; closeInspection: string; closeResults: string; collapseRail: string; expandRail: string; consoleControls: string; consoleUnavailable: string; critical: string; currentRisk: string; currentRoute: string; delay: string; delete: string; deleteConsequence: string; deleteVehicle: string; destination: string; dimensions: string; driverTab: string; driving: string; drivingRestRisk: string; eta: string; fleetFilters: string; fleetNumber: string; followVehicle: string; frozen: string; help: string; heightComparison: string; hoursShort: string; identity: string; impact: string; invalidLabel: string; label: string; labelSaved: string; language: string; languageEnglish: string; languageSpanish: string; length: string; meters: string; minutes: string; minutesShort: string; needsAttention: string; noCurrentRisk: string; notAvailable: string; operationalMap: string; operationalSummary: string; origin: string; plate: string; priority: string; priorityCritical: string; priorityStandard: string; priorityUrgent: string; refrigeration: string; remainingDrive: string; restDeadline: string; resting: string; retry: string; riskClosure: string; riskComparison: string; riskHeight: string; riskImpactClosure: string; riskImpactHeight: string; riskImpactRest: string; riskImpactSnow: string; riskImpactWeight: string; riskRest: string; riskSnow: string; riskWeight: string; roadRestrictionIssues: string; route: string; saveLabel: string; selectVehicle: string; status: string; statusCritical: string; statusDriving: string; statusNeedsAttention: string; statusResting: string; tonnes: string; vehicleHeight: string; vehicleInspection: string; vehicleTab: string; vehicleType: string; viewOnRoute: string; weatherAffected: string; webMcpChecking: string; webMcpRequired: string; weight: string; whyAttention: string;
};

const catalogs: Record<Locale, Catalog> = { en, es };
const filterKeys: Record<FilterCategory, keyof Catalog> = { all: "all", resting: "resting", "needs-attention": "needsAttention", critical: "critical", "weather-affected": "weatherAffected", "driving-rest-risk": "drivingRestRisk", "road-restriction-issues": "roadRestrictionIssues" };

export function catalog(locale: Locale = "en"): Catalog { return catalogs[locale]; }
export function filterLabel(category: FilterCategory, locale: Locale = "en"): string { return catalog(locale)[filterKeys[category]]; }
export function interpolate(template: string, values: Record<string, string | number>): string { return Object.entries(values).reduce((message, [key, value]) => message.replaceAll(`{${key}}`, String(value)), template); }

export type OperationalCopy = { activeFilters: string; closeOverview: string; lowClearance: string; openOverview: string; operationalOverview: string; removeFilter: string; restDeadlineRisk: string; roadClosure: string; severeWeather: string; severityCritical: string; severityHigh: string; severityLow: string; severityMedium: string; weightRestriction: string };
const operationalCatalogs: Record<Locale, OperationalCopy> = {
  en: { activeFilters: "{count} active filters", closeOverview: "Close operational overview", lowClearance: "Low clearance", openOverview: "Open operational overview", operationalOverview: "Operational overview", removeFilter: "Remove {filter}", restDeadlineRisk: "Driving and rest deadline", roadClosure: "Road closure", severeWeather: "Severe weather", severityCritical: "Critical", severityHigh: "High", severityLow: "Low", severityMedium: "Medium", weightRestriction: "Weight restriction" },
  es: { activeFilters: "{count} filtros activos", closeOverview: "Cerrar resumen operativo", lowClearance: "Gálibo reducido", openOverview: "Abrir resumen operativo", operationalOverview: "Resumen operativo", removeFilter: "Quitar {filter}", restDeadlineRisk: "Límite de conducción y descanso", roadClosure: "Carretera cerrada", severeWeather: "Meteorología adversa", severityCritical: "Crítica", severityHigh: "Alta", severityLow: "Baja", severityMedium: "Media", weightRestriction: "Restricción de peso" },
};
export function operationalCopy(locale: Locale): OperationalCopy { return operationalCatalogs[locale]; }

export type RecoveryComparisonCopy = { alternative: string; alternativeAvoids: string; alternativeAvoidanceUnknown: string; backToVehicleDetails: string; beforeDeparture: string; bufferSupplied: string; clearanceIncident: string; comparison: string; current: string; currentRouteIncident: string; distance: string; domainConnected: string; duration: string; exclusionZone: string; exactZone: string; faster: string; failureDescription: string; failureTitle: string; hardConstraints: string; incident: string; incidentDetail: string; keepCurrent: string; longer: string; noChange: string; noRouteChanged: string; noUnknown: string; preparePlan: string; previewOnly: string; reasonCode: string; rejected: string; rejectionExplanation: string; required: string; requiredSuffix: string; resolvedRisk: string; reviewOptions: string; routeOptions: string; routeStarted: string; safetyMargin: string; selectIncident: string; shorter: string; slower: string; stillUnknown: string; supported: string; useAlternative: string; vehicleHeight: string; visualReview: string };
const recoveryComparisonCatalogs: Record<Locale, RecoveryComparisonCopy> = {
  en: { alternative: "Alternative", alternativeAvoids: "Avoids the mapped exclusion zone.", alternativeAvoidanceUnknown: "Exclusion-zone avoidance is not confirmed.", backToVehicleDetails: "Back to vehicle details", beforeDeparture: "Before departure", bufferSupplied: "Clearance buffer supplied by the pre-dispatch operation.", clearanceIncident: "Clearance incident", comparison: "Recovery comparison", current: "Current", currentRouteIncident: "The current route reaches a {restriction} m clearance before departure.", distance: "Distance", domainConnected: "Domain connected", duration: "Duration", exclusionZone: "Exclusion zone", exactZone: "Exact {radius} m zone", faster: "faster", failureDescription: "The pre-dispatch operation returned a structured failure, so route options cannot be shown safely.", failureTitle: "Recovery comparison unavailable", hardConstraints: "Hard human constraints", incident: "{restriction} m incident", incidentDetail: "Incident detail", keepCurrent: "Keep current route", longer: "longer", noChange: "No change", noRouteChanged: "No route was changed.", noUnknown: "No additional uncertainty fields were returned by this operation.", preparePlan: "Prepare plan", previewOnly: "Preview only — no plan will be prepared.", reasonCode: "Reason code", rejected: "Rejected", rejectionExplanation: "Required clearance exceeds the mapped restriction.", required: "Required", requiredSuffix: "m required", resolvedRisk: "Resolved risk", reviewOptions: "Review recovery options", routeOptions: "Route options", routeStarted: "Route started", safetyMargin: "Safety margin", selectIncident: "Select Unit 211 clearance incident", shorter: "shorter", slower: "slower", stillUnknown: "Still unknown", supported: "Supported for comparison", useAlternative: "Use alternative route", vehicleHeight: "Vehicle height", visualReview: "Visual review" },
  es: { alternative: "Alternativa", alternativeAvoids: "Evita la zona de exclusión cartografiada.", alternativeAvoidanceUnknown: "No se ha confirmado que evite la zona de exclusión.", backToVehicleDetails: "Volver al detalle del vehículo", beforeDeparture: "Antes de la salida", bufferSupplied: "Margen de gálibo suministrado por la operación previa a la salida.", clearanceIncident: "Incidencia de gálibo", comparison: "Comparación de recuperación", current: "Actual", currentRouteIncident: "La ruta actual alcanza un gálibo de {restriction} m antes de la salida.", distance: "Distancia", domainConnected: "Conectada al dominio", duration: "Duración", exclusionZone: "Zona de exclusión", exactZone: "Zona exacta de {radius} m", faster: "más rápida", failureDescription: "La operación previa a la salida devolvió un fallo estructurado, por lo que las opciones de ruta no pueden mostrarse de forma segura.", failureTitle: "Comparación de recuperación no disponible", hardConstraints: "Restricciones humanas estrictas", incident: "Incidencia de {restriction} m", incidentDetail: "Detalle de la incidencia", keepCurrent: "Mantener la ruta actual", longer: "más larga", noChange: "Sin cambios", noRouteChanged: "No se modificó ninguna ruta.", noUnknown: "La operación no devolvió campos de incertidumbre adicionales.", preparePlan: "Preparar plan", previewOnly: "Sólo preview. No se preparará ningún plan.", reasonCode: "Código de motivo", rejected: "Rechazada", rejectionExplanation: "El gálibo requerido supera la restricción cartografiada.", required: "Requerido", requiredSuffix: "m requeridos", resolvedRisk: "Riesgo resuelto", reviewOptions: "Revisar opciones de recuperación", routeOptions: "Opciones de ruta", routeStarted: "Ruta iniciada", safetyMargin: "Margen de seguridad", selectIncident: "Seleccionar incidencia de gálibo de Unit 211", shorter: "más corta", slower: "más lenta", stillUnknown: "Aún desconocido", supported: "Compatible para comparar", useAlternative: "Usar la ruta alternativa", vehicleHeight: "Altura del vehículo", visualReview: "Revisión visual" },
};
export function recoveryComparisonCopy(locale: Locale): RecoveryComparisonCopy { return recoveryComparisonCatalogs[locale]; }
